### ISSUE TITLE
Double right click does not mark to beginning of line

### ISSUE THREAD

**Issue by schierlm** [andreaspirklbauer/Oberon-experimental#1]
Is this intentional?

I used to mark whole lines by double-clicking the last character (or after the last character) and also used it a lot to mark the `pos` for `Edit.Locate`, but it does not work in Experimental Oberon.

To compare:

[Vanilla Oberon](https://schierlm.github.io/OberonEmulator/emu.html#VanillaDiskImage,1024,576)
[Experimental Oberon](https://schierlm.github.io/OberonEmulator/emu.html#OberonExperimentalDiskImage,1024,576)

**Comment by andreaspirklbauer** [comment]
It's back.
