### ISSUE TITLE
Upgrade path from older Experimental Oberon?

### ISSUE THREAD

**Issue by schierlm** [andreaspirklbauer/Oberon-experimental#2]
I'm trying to upgrade my Experimental Oberon v1.0 (as of end of 2016) to the current version v1.0 (moving v1.0 around is a bit irritating, isn't it?)

However, it seems the structure of Modules.ModDesc has changed quite a lot, and my old structure neither matches the structure of Modules0 nor the structure of Modules. Therefore, neither bootstrapping using Modules0, nor "just recompiling" gave me a bootable system.

My old Modules looked like this:

```
MODULE Modules; (*Link and load on RISC; NW 20.10.2013 / 9.4.2016 / AP 12.12.90 / 12.12.16*)
  IMPORT SYSTEM, Kernel, Files;
  CONST versionkey = 1X; MT = 12; DescSize = 88;

  TYPE Module* = POINTER TO ModDesc;
    Command* = PROCEDURE;
    ModuleName* = ARRAY 32 OF CHAR;

    ModDesc* = RECORD
        name*: ModuleName;
        next*: Module;
        key*, num*, size*, refcnt*: INTEGER;
        data*, var*, str*, code*, imp*, cmd*, ent*, ptr*, pvar*: INTEGER (*addresses*)
      END ;
```

Is there an upgrade path available, or does using Experimental Oberon mean that you should be prepared to either start fresh from a new disk image from you, or to bootstrap again from vanilla?

I now bootstrapped it again from vanilla, and applied my own modifications again, which worked fine (only that it took me 45 minutes :D)

**Comment by andreaspirklbauer** [comment]
The structure of the module descriptor, the object file format and the module loader have changed since the version from the end of 2016, and there is indeed no upgrade path from THAT version.

One could of course prepare one (15-30min of work). But I saw no need for that - you seem to be the only person who was still on that version. Is it a problem for you to start afresh from Original Oberon? Note that in the future I don't plan to make changes to the module descriptor and object format without also adding an upgrade path.

Note also that the github page of Experimental Oberon also contains an *image* of Experimental Oberon (for the emulator though, so probably not useful for your purposes).

**Comment by andreaspirklbauer** [comment]
And.. in the future there will be proper versioning (didn't see any need for that either so far, as much of the work done so far was considered in a kind of pre-alpha-release stage, which only happened to be online since a few people asked for it).

**Comment by schierlm** [comment]
It's ok. I just would not call a piece of software (regardless how much "experimental" is in its name) 1.0 if it it is in pre-alpha stage...

To quote [Eric S. Raymond](http://catb.org/~esr/writings/homesteading/homesteading/ar01s13.html) here:
> In the closed-source world, Version 1.0 means "Don't touch this if you're prudent."; in the open-source world it reads something more like "The developers are willing to bet their reputations on this."

Or you can also ask [Semantic Versioning](http://semver.org/), which is generally for libraries, but I think it can be adapted elsewhere too:

> Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable.
> Version 1.0.0 defines the public API. The way in which the version number is incremented after this release is dependent on this public API and how it  changes.

Anyway, thanks for your feedback, I know now that I did not miss anything and to be prepared for a bumpy ride in the future too :-)

**Comment by andreaspirklbauer** [comment]
Ok. Glad you solved the issue for your case (ps: I don't care what other people think about version naming)

**Comment by schierlm** [comment]
Sorry. My fault. I should have thought of that, considering that you do not care what other people think about repository history either. :P
